### ISSUE TITLE
Post type list display if there been attachment to post or not

### ISSUE THREAD

**Issue by Akrasnovskis** [CMB2/cmb2-attached-posts#50]
Hello Guys,

My PHP knowledge a bit poor, but is there any options that I can add a line of code that will display in the list of posts if to that has been attached the file as PDF for example.

So if you go to post type you have the list of posts, there are columns, like Name, Categories, Tags and Date published, but is there any options to have an extra column called "Attachment" and bellow show like a paperclip, if not then is just empty.

Thanks in advance

![screen shot 2017-11-09 at 12 37 29](https://user-images.githubusercontent.com/3071081/32605994-77b690ba-c54b-11e7-98bf-499c08a36d48.png)

**Comment by jtsternberg** [comment]
Are specifically asking in reference to this plugin? Are you attaching pdfs vis this plugin/field type?

**Comment by jtsternberg** [comment]
If so, using the [example field setup](https://github.com/CMB2/cmb2-attached-posts/blob/master/example-field-setup.php), you can add column output this way:
```php

$example_meta->add_field( array(
	'name'    => __( 'Attached Posts', 'cmb2' ),
	'desc'    => __( 'Drag posts from the left column to the right column to attach them to this page.<br />You may rearrange the order of the posts in the right column by dragging and dropping.', 'cmb2' ),
	'id'      => 'attached_cmb2_attached_posts',
	'type'    => 'custom_attached_posts',
	'options' => array(
		'show_thumbnails' => true, // Show thumbnails on the left
		'filter_boxes'    => true, // Show a text box for filtering the results
		'query_args'      => array(
			'posts_per_page' => 10,
			'post_type'      => 'page',
		), // override the get_posts args
	),
	'column' => array(
		'position' => 2, // Where you want the column
		'name' => 'Attached Posts',
	),
	'display_cb' => function( $args, $field ) {
		// You can output whatever you want here.
		if ( ! empty( $field->value ) ) {
			echo '<ul>';
			foreach ( (array) $field->value as $id ) {
				printf(
					'<li>&ndash; <a href="%s">%s</a></li>',
					get_edit_post_link( $id ),
					get_the_title( $id )
				);
			}
			echo '</ul>';
		}
	},
) );
```
