### ISSUE TITLE
PHP Warning:  Use of undefined constant CMB2_ATTACHED_POSTS_FIELD_VERSION

### ISSUE THREAD

**Issue by cgarofalo** [CMB2/cmb2-attached-posts#62]
Full error message: 

```[27-Aug-2020 20:21:12 UTC] PHP Warning:  Use of undefined constant CMB2_ATTACHED_POSTS_FIELD_VERSION - assumed 'CMB2_ATTACHED_POSTS_FIELD_VERSION' (this will throw an Error in a future version of PHP) in /vagrant/content/mu-plugins/cmb2-attached-posts/init.php on line 38```

This is happening with PHP 7.4, eventually this will likely break in PHP 8.

**Comment by cgarofalo** [comment]
Ugh. I figured it out, I was initializing the plugin with `init.php` instead of `cmb2-attached-posts-field.php`. Maybe this will help someone else out!

**Comment by tw2113** [comment]
That happens sometimes, and glad you got this figured out.
